import type { FishCatalogEntry } from '../../defs/def-record';

export const defaultFishCatalog: FishCatalogEntry[] = [
	{fishName: 'Anchovy', baseline: 2.5},
	{fishName: 'Angelfish', baseline: 6},
	{fishName: 'Barracuda', baseline: 200},
	{fishName: 'Betta', baseline: 1},
	{fishName: 'Blue Whale', baseline: 4200000},
	{fishName: 'Bluegill', baseline: 16},
	{fishName: 'Carp', baseline: 400},
	{fishName: 'Catfish', baseline: 50},
	{fishName: 'Clownfish', baseline: 3},
	{fishName: 'Cod', baseline: 350},
	{fishName: 'Electric Eel', baseline: 704},
	{fishName: 'Flounder', baseline: 10},
	{fishName: 'Flying Fish', baseline: 12},
	{fishName: 'Goldfish', baseline: 15},
	{fishName: 'Great White', baseline: 25000},
	{fishName: 'Guppy', baseline: 0.1},
	{fishName: 'Halibut', baseline: 950},
	{fishName: 'Hammerhead', baseline: 8100},
	{fishName: 'Herring (Red)', baseline: 37},
	{fishName: 'Jellyfish', baseline: 8},
	{fishName: 'Koi', baseline: 175},
	{fishName: 'Kraken', baseline: 5000000},
	{fishName: 'Largemouth Bass', baseline: 45},
	{fishName: 'Lionfish', baseline: 40},
	{fishName: 'Mackerel', baseline: 35},
	{fishName: 'Mahi-mahi', baseline: 17},
	{fishName: 'Manta Ray', baseline: 48000},
	{fishName: 'Marlin', baseline: 16000},
	{fishName: 'Moray Eel', baseline: 550},
	{fishName: 'Oarfish', baseline: 4500},
	{fishName: 'Octopus', baseline: 1200},
	{fishName: 'Perch', baseline: 14},
	{fishName: 'Pike', baseline: 32},
	{fishName: 'Piranha', baseline: 28},
	{fishName: 'Pufferfish', baseline: 24},
	{fishName: 'Rainbow Trout', baseline: 48},
	{fishName: 'Red Snapper', baseline: 64},
	{fishName: 'Sailfish', baseline: 600},
	{fishName: 'Salmon', baseline: 56},
	{fishName: 'Sardine', baseline: 5.5},
	{fishName: 'Smallmouth Bass', baseline: 39},
	{fishName: 'Squid', baseline: 17500},
	{fishName: 'Steve', baseline: 4200},
	{fishName: 'Sturgeon', baseline: 43},
	{fishName: 'Sunfish', baseline: 35280},
	{fishName: 'Swordfish', baseline: 2400},
	{fishName: 'Tetra', baseline: 0.05},
	{fishName: 'Tuna', baseline: 8000},
	{fishName: 'Walleye', baseline: 36},
	{fishName: 'Yellowtail', baseline: 250},
];
