import type { HorseCatalogEntry } from "../../defs/def-record";

export const defaultHorseCatalog: HorseCatalogEntry[] = [
    {horseName: 'American Scarecrow'},
    {horseName: 'Secretary'},
    {horseName: 'Gol D. Ship'},
    {horseName: 'Hot Shots!'},
    {horseName: 'Seis Siete'},
    {horseName: 'The Horse Formerly Known As McQueen'},
    {horseName: 'My Fat Chud Son'},
    {horseName: 'Fillyvester Staillion'},
    {horseName: 'MOPAR Gen 3 6.4L Apache HEMI'},
    {horseName: 'Miku Miku BEEAAAAAAAAAAAAAAAAAAAM!'},
    {horseName: 'Ocean Pretzel'},
    {horseName: 'Hoborse II'},
    {horseName: 'Bossman'},
    {horseName: 'Consul Incitatus'},
    {horseName: 'OG Hindu Kush'},
    {horseName: 'Super Horsey Ball'},
    {horseName: 'Al Capony'},
    {horseName: 'Hoof Hearted'},
    {horseName: 'Fish'},
    {horseName: 'Pretty Pickles'},
    {horseName: 'Mr. Feet'},
    {horseName: 'Donkey Devito'},
    {horseName: 'Perky Berky'},
    {horseName: 'Rainbow Crash'},
    {horseName: 'Horseratio Nelson'},
    {horseName: 'Horsechata'},
    {horseName: 'Horse Shaped Unusually Like 124 Rats Wearing a Trenchcoat'},
    {horseName: 'Horse Shaped Usually Like 124 Rats Wearing a Trenchcoat, But Today Is Different'},
    {horseName: 'Mayo Neighs'},
    {horseName: 'Whipping (Out) My Sonic the Horse Hog'},
    {horseName: 'Without Overtelling'},
    {horseName: 'Bought with My Swear Jar Money'},
    {horseName: 'Bought with Your Swear Jar Money'},
    {horseName: 'The Poopmobile'},
    {horseName: 'Recommended Daily Dose'},
    {horseName: 'Dark Souls II'},
    {horseName: 'Sofa King Horse'},
    {horseName: 'Good Neigh-bor'},
    {horseName: 'Bad Neigh-bor'},
    {horseName: 'The Creepy Neigh-bor Who Stares In Your Windows'},
    {horseName: 'Franz Herdinand'},
];